### ISSUE TITLE
It seems you missed xxxhdpi resolution for android

### ISSUE THREAD

**Issue by dipen-apptrait** [alensunny/design_automator_services#1]

**Comment by alensunny** [comment]
As per official Android documentation "You do not need to provide xxxhdpi assets for all your app's images."
xxxhdpi is only required for AppIcon.

When you create UI designs in 1080x1920 in Photoshop 72dpi it is xxhdpi. This service is to generate all UI assets you used for the application, not for AppIcon. For AppIcon I recommend you to use Android Asset Studio in Chrome browser

**Comment by alensunny** [comment]
Updated the script
